FORMAT: 1A
HOST: https://www.caa.com/api/v1

# Aircraft Registration API

This API exposes registration data and additional functionalities to enable developers and interested parties build applications and tools that utilize the data in the registry. The API is JSON-rest based and uses standard HTTP response codes to indicate API errors and successes.

#### Token Authentication
The registration data is exposed via a OAUTH token that is linked to a user account on the system. To generate a OAUTH token and credentials you must first create a account and follow instructions at the [Token Generation page](https://www.caa.com/accounts/token/) on our website. If your account is for specific law enforcement bodies or regulatory bodies, you will be required to request privileged access, you can get your tokens by filling out the form here [Privileged Access request](https://www.caa.com/accounts/token/) 

#### Access
This API supports only **https://** connections via the API. ``http://`` connections will be given a automatic HTTP 301 response.

#### Read-only
This API supports only data to be __read__ out of the registry. At this moment, we do not support write calls into the registry. It is assumed that the writes will be done through a different workflow that require additional documentation. This registry API can easily be extended to make write calls as well. 

#### Pagination
API responses are paginated. The default page size is 20; you can alter this by adding the ``page_size`` parameter to your request.

#### Limits
The API system throttles reqests to 1000 per hour for a particular token after which it will deny repeated requests for 30 minutes. If you require unthrottled access, please contact us using the [Special Access request](https://www.caa.com/accounts/privileged/). For more information please review [Identity and Authentication](https://github.com/openskies-sh/aircraftregistry/blob/master/documents/registration-identity-authentication.md) document.

#### Response Codes
The API uses standard HTTP response codes to communicate the status of the request. In general, 2xx codes signify success and 4xx codes signify failure, and these codes are generally associated with an invalid parameter being provided in the request. A 5xx code is a general server failure on our side. Please contact our support team if you encounter 5xx errors. Please refer to the Wikipedia page on [HTTP request codes](https://www.wikipedia.org/HTTP_Respose_Codes/) for more information 

## Group Operator API
Resources related to Operator Registration in the API


## All Operators [/operators/]

### List all operators [GET]

***Scope read:operator***


Returns a list of operators in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)
        
        [
            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "website": "august.com",
                "email": "aj@august.com",
                "phone_number": "+497221816880"
            },
            {
                "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                "company_name": "Electric Inspection",
                "website": "electricinspection.com",
                "email": "contact@electricinspection.com",
                "phone_number": "+4930292487"
            }
        ]

## Single Operator Details [/operators/{operatorid}/]

### Get a single operator [GET]

***Scope read:operator read:operator:all***


Returns all the details of a single operator available in the database. The operator id is the unique ID assoicated with the operator that is in the form of a uuid.

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        + website: aalto.fi (string) - Web address of operator

    + Body

            
            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "website": "august.com",
                "email": "aj@august.com",
                "phone_number": "+497221816880"
            }

## Privileged Single Operator Details [/operators/{operatorid}/privileged/]

### Get a operator (Privileged) [GET]


***Scopes read:operator read:operator:all read:operator:privileged***


This is a privileged request made by a interested party that has special access privileges in the registry. Returns all the details of a single operator available in the database. The operatorid is the unique ID assoicated with the operator that is in the form of a uuid. 

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        + website: aalto.fi (string) - Web address of operator
        + address: Otakaari 24 (string) - Postal Address of the operator
        + postcode: 2150 (number) - Postcode of the registered office of the opeartor

    + Body

            
            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "country": "NA",
                "website": "august.com",
                "email": "aj@august.com",
                "operator_type": 0,
                "address": {
                    "id": "8ddda026-2995-44ef-9eab-55e396eaef0d",
                    "address_line_1": "Claureen Lahinch rd Ennis",
                    "address_line_2": "",
                    "address_line_3": "",
                    "postcode": "D02VE22",
                    "city": "Westport",
                    "country": "IE",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "operational_authorizations": [
                    "SORA"
                ],
                "authorized_activities": [
                    "videotaping",
                    "photographing"
                ],
                "created_at": "2018-09-04T12:20:30Z",
                "updated_at": "2018-09-04T12:20:30Z"
            }


## Operator Aircraft Details [/operators/{operatorid}/aircraft]

### Get aircraft for operator [GET]

***Scope read:operator read:operator:all read:aircraft,read:aircraft:all***


Returns all the details of a single operator available in the database. The operator id is the unique ID assoicated with the operator that is in the form of a uuid.

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + mass: 300 (number) - Mass of the aircraft
        + manufacturer: 6f9cd973-15b9-4066-b4d0-1e8bbd0f279d (string) - ID of the manufacturer in the registry
        + esn: 6f9cd973-15b9-4066-b4d0-1e8bbd0f279d (string) - Electronic serial number of the aircraft
        + maci_number: 86ac-42dc-8d19 (string) - MACI Number of the aircraft
        + status: 1 (number) - 1 if aircraft is active and in service, 0 if not 
        + registration_mark: EF3FE (string) - Registration mark on the aircraft
        + category: Fixed Wing (string) - Category of the aircraft
        + master_series: null (string) - Master Series of the aircraft if available
        + series: null (string) - Series of the aircraft if available
        + photo: null (string) - URL to the photo of the aircraft
        + photo_small: null (string) - URL to a small  photo of the aircraft
        + sub_category: null (string) - Sub-category of aircraft if available
        + icao_aircraft_type_designator: null (string) - ICAO aircraft type if available
        + max_certified_takeoff_weight: null (string) - Maximum certified take off weight
        

    + Body
            
            [
                {
                    "id": "0797d9ef-02d9-41cf-93ff-439aaf1609ae",
                    "mass": 300,
                    "manufacturer": "6f9cd973-15b9-4066-b4d0-1e8bbd0f279d",
                    "model": "Parrot",
                    "esn": "4D4652310000000000000000313233343436373839414243",
                    "maci_number": "86ac-42dc-8d19",
                    "status": 1,
                    "registration_mark": null,
                    "category": "FIXED WING",
                    "type_certificate": {
                        "id": "75f358c6-e8d3-46aa-a3de-172bdcea469d",
                        "type_certificate_id": "1dc42b2a-7e3f-4e87-b23d-353ec8a06705",
                        "type_certificate_issuing_country": "IRE",
                        "type_certificate_holder": "Agro Products Inc.",
                        "type_certificate_holder_country": "IRE"
                    },
                    "created_at": "2018-09-04T12:20:30Z",
                    "master_series": null,
                    "series": null,
                    "popular_name": "Parrot 2",
                    "photo": null,
                    "photo_small": null,
                    "sub_category": "UAV",
                    "icao_aircraft_type_designator": "HS20",
                    "max_certified_takeoff_weight": "0.000",
                    "updated_at": "2018-09-04T12:20:30Z"
                }
            ]
                


## Group Contact API
Resources related to Contacts with in the Registration in the API


## All Contacts [/contacts/]

### List all contacts [GET]

***Scope read:contact read:operator:all read:person***

Returns a list of contact people in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)
                    
                    
            [
                {
                    "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                    "operator": {
                        "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                        "company_name": "A.J. August Photography",
                        "website": "august.com",
                        "email": "aj@august.com",
                        "phone_number": "+497221816880"
                    },
                    "person": {
                        "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                        "first_name": "Catherine",
                        "middle_name": null,
                        "last_name": "OConor",
                        "email": "catherine@gmail.com",
                        "created_at": "2018-09-04T12:20:30Z",
                        "updated_at": "2018-09-04T12:20:30Z"
                    },
                    "role_type": 0,
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                {
                    "id": "c3ae2bb0-19f6-4738-a53b-cdb0acbaf5b1",
                    "operator": {
                        "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                        "company_name": "Electric Inspection",
                        "website": "electricinspection.com",
                        "email": "contact@electricinspection.com",
                        "phone_number": "+4930292487"
                    },
                    "person": {
                        "id": "a2f3b8b2-183d-44df-9254-83aca26d01c0",
                        "first_name": "Molly",
                        "middle_name": "S",
                        "last_name": "Storey",
                        "email": "molly@hotmail.com",
                        "created_at": "2018-09-04T12:20:30Z",
                        "updated_at": "2018-09-04T12:20:30Z"
                    },
                    "role_type": 1,
                    "updated_at": "2018-09-04T12:20:30Z"
                }
            ]


## Single Contact Details [/contacts/{contactid}/]

### Get a single contact [GET]

***Scope read:contact read:person***

Returns all the details of a single contact and basic information about the contact person available in the database. The contact id is the unique ID assoicated with a contact person for the operator that is in the form of a uuid.

+ Parameters
    + contactid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a contact person for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + contact_name: Aalto Korkeakoulusäätiö (string) - Name of the contact person in the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        

    + Body


            {
                "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "person": {
                    "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                    "first_name": "Catherine",
                    "middle_name": null,
                    "last_name": "OConor",
                    "email": "catherine@gmail.com",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "role_type": 0,
                "updated_at": "2018-09-04T12:20:30Z"
            }


## Privileged Single Contact Details [/contacts/{contactid}/privileged]

### Get a single contact [GET]

***Scope read:contact read:contact:all read:contact:privileged read:address:all read:person:all***

Returns all the details of a single contact and basic information about the contact person available in the database. The contact id is the unique ID assoicated with a contact person for the operator that is in the form of a uuid.

+ Parameters
    + contactid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a contact person for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + contact_name: Aalto Korkeakoulusäätiö (string) - Name of the contact person in the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        

    + Body


            {
                "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "address": {
                    "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                    "address_line_1": "Malroc House, South Mall",
                    "address_line_2": "",
                    "address_line_3": "",
                    "postcode": "D02PT89",
                    "city": "Singapore",
                    "country": "SG",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "person": {
                    "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                    "first_name": "Catherine",
                    "middle_name": null,
                    "last_name": "OConor",
                    "email": "catherine@gmail.com",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "operational_authorizations": [
                    "SORA"
                ],
                "authorized_activities": [
                    "videotaping",
                    "photographing"
                ],
                "created_at": "2018-09-04T12:20:30Z",
                "updated_at": "2018-09-04T12:20:30Z"
            }

## Group Pilot API
Resources related to Pilots with in the Registration in the API


## All Pilots [/pilots/]

### List all pilots [GET]

***Scope read:pilot read:pilot:privileged read:person:privileged read:address:privileged***


Returns a list of pilots in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

        [
            {
                "id": "d4b8aa2c-0a52-4adc-806a-f363deb6a1e0",
                "created_at": "2018-09-04T12:20:30Z",
                "updated_at": "2018-09-04T12:20:30Z"
            },
            {
                "id": "2f15a395-65a3-4a73-a492-57c7c470d527",
                "created_at": "2018-09-04T12:20:30Z",
                "updated_at": "2018-09-04T12:20:30Z"
            }
        ]
        
                

## Single Pilot Details [/pilots/{pilotid}]

### Get a single pilot [GET]

***Scope read:pilot read:person read:person:all***

Returns all the details of a single pilot and basic information about the pilot available in the database. The pilot id is the unique ID assoicated with a pilot for the operator that is in the form of a uuid.

+ Parameters
    + pilotid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a pilot for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Body

    
            {
                "id": "d4b8aa2c-0a52-4adc-806a-f363deb6a1e0",
                "is_active": true,
                "tests": [],
                "updated_at": "2018-09-04T12:20:30Z",
                "created_at": "2018-09-04T12:20:30Z",
                "person": {
                    "id": "32153c3b-663b-41e4-afc2-47127a713704",
                    "first_name": "Mickey",
                    "middle_name": "Richard",
                    "last_name": "Matheny",
                    "email": "MickeyRMatheny@teleworm.us",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                }
            }
            

## Privileged Single Pilot Details [/pilots/{pilotid}/privileged]

### Get a single pilot (Privileged) [GET]

***Scope read:pilot read:pilot:all read:pilot:privileged read:person:privileged read:address:privileged***

Returns all the details of a single pilot and basic information about the pilot available in the database. The pilot id is the unique ID assoicated with a pilot for the operator that is in the form of a uuid.

+ Parameters
    + pilotid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a pilot for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
+ Response 200 (application/json)

    + Body

            {
                "id": "d4b8aa2c-0a52-4adc-806a-f363deb6a1e0",
                "operator": {
                    "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                    "company_name": "Electric Inspection",
                    "website": "electricinspection.com",
                    "email": "contact@electricinspection.com",
                    "phone_number": "+4930292487"
                },
                "is_active": true,
                "tests": [],
                "address": {
                    "id": "28b2f84c-6798-49b9-9114-97d1d14f49f2",
                    "address_line_1": "8 Biscay Rd, Sorrento",
                    "address_line_2": "",
                    "address_line_3": "",
                    "postcode": "NR24 7DZ",
                    "city": "SHARRINGTON",
                    "country": "GB",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "person": {
                    "id": "32153c3b-663b-41e4-afc2-47127a713704",
                    "first_name": "Mickey",
                    "middle_name": "Richard",
                    "last_name": "Matheny",
                    "email": "MickeyRMatheny@teleworm.us",
                    "created_at": "2018-09-04T12:20:30Z",
                    "updated_at": "2018-09-04T12:20:30Z"
                },
                "updated_at": "2018-09-04T12:20:30Z",
                "created_at": "2018-09-04T12:20:30Z"
            }
            


## Group Aircraft API
Resources related to Aircraft with in the Registration in the API


## All Aircraft [/aircrafts/]

### List all Aircraft [GET]

***Scope read:aircraft***

List all aircraft in the registry

+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
    + Body

            {
              "manufacturer": "DJI",
              "model": "Parrot",
              "mass": "300",
              "esn": "5G6532640000000000000000823050083171098833641055",
              "maci_number": "3d9-23",
              "status": "active"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "mass": {
                  "type": "number"
                },
                "esn": {
                  "type": "string"
                },
                "maci_number": {
                  "type": "string"
                }
              }
            }
            
+ Response 200 (application/json)

            {
              "equipment_id": "26bc3e7710ea"
            }
    

## Single Aircraft Details [/aircrafts/{aircraftid}]

### Get a single Aircraft [GET]

***Scope read:aircraft read:aircraft:all read:aircraft:privileged***

Get information about a Aircraft by looking up its ESN

+ Parameters
    + aircraftid: 4D4652310000000000000000313233343436373839414243 (string) - ESN of Aircraft, ESN = [Manufacturer’s Code] [Serial Number] [IMEISV] [Performative Characteristics]

    
+ Request (application/json)
    + Headers

            Authorization: Bearer ABC123
            
    + Body

            {
              "status": "inactive"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "mass": {
                  "type": "number"
                },
                "esn": {
                  "type": "string"
                },
                "maci_number": {
                  "type": "string"
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "equipment_id": "26bc3e7710ea",
                "manufacturer": "DJI",
                "model": "Parrot",
                "mass": "300",
                "esn": "5G6532640000000000000000823050083171098833641055",
                "maci_number": "3d9-23",
                "status": "active",
                "created_at": "2011-04-10T20:09:31Z",
                "updated_at": "2014-03-03T18:58:10Z"
            }
   